### ISSUE TITLE
demo site is not working 

### ISSUE THREAD

**Issue by noklam** [Netflix/metaflow-ui#138]
### Description
This[ medium blog](https://netflixtechblog.com/open-sourcing-a-monitoring-gui-for-metaflow-75ff465f0d60) lead me to the GUI, I want to have a look at the GUI to learn about the tool more.

The [demo link](https://demo.public.outerbounds.xyz/) doesn't seem to work anymore, is it being deprecated?

**Comment by obgibson** [comment]
Thanks for picking this up.

I have asked around, and yes, the demo GUI has been deprecated.

**Comment by noklam** [comment]
Got it, thanks I will try to build from source then.
