### ISSUE TITLE
Time zone selection does not seem to adapt to daylight saving

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow-ui#38]
### Description

If I select America/Los Angeles as my timezone, it is marked as GMT-7 but the current time should be GMT-8.

### Steps to Reproduce

1. Select the America/Los Angeles time zone
2. Notice that things are off by 1h.
3. Selecting the America/Juneau timezone makes it all work :) .

**Expected behavior:**

Timezone would respect daylight saving.

**Actual behavior:**

Timezone selection does not respect daylight saving.

**Reproduces how often:**

Always

### Versions
Application version: v1.0.2
Service version: 2.1.0-2021-11-15 16:13:11 PST-15cd9f7fa9d5df15d9fe7dac6a60667383c4fa6b|75ca8de715480c84198fbde993908e6a9cb9747d

### Additional Information

Internal deployment at Netflix.

**Comment by oavdeev** [comment]
I've ran into this as well. 

AFAIK to make this work reliably in all cases, you'd have to have some mechanism to [update tzdata pretty frequently](https://data.iana.org/time-zones/tzdb/NEWS). One idea here: if that's easier to implement and maintain, maybe we could replace the existing TZ selector with a simple switch between UTC and browser timezone.
