### ISSUE TITLE
Tags do not seem to update when present in the URL but also in the session

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow-ui#54]
### Description

If I go to the UI with a given tag in the URL (ie: `&_tags=XYZ`) but I had previously been on the UI with a tag `ABC` selected, the tag in the UI is ignored and only the tag that was previously selected i used.

### Steps to Reproduce

This is always reproducible as described above.

### Versions

Application version: v1.0.2
Service version: 2.1.0-2021-11-15 16:13:11 PST-15cd9f7fa9d5df15d9fe7dac6a60667383c4fa6b|75ca8de715480c84198fbde993908e6a9cb9747d

**Comment by rsanteri** [comment]
Good find. Here is PR to fix it https://github.com/Netflix/metaflow-ui/pull/56

**Comment by obgibson** [comment]
Fixed
