### ISSUE TITLE
Cards always display with height == 0px

### ISSUE THREAD

**Issue by PytLab** [Netflix/metaflow-ui#74]
### Description
Tried to create a card with Markdown and HTML template, the card section shows nothing. like below
![image](https://user-images.githubusercontent.com/8553710/178662433-a285e50a-8ec9-4512-b92c-b58ab7fd3590.png)

I checked the iframe style, it shows the `"height: 0px"`, if I change the value of height to 200px for example, then it can be displayed correctly.

### Steps to Reproduce

1. Metaflow step code example
```python
    @card(type='blank')
    @step
    def start(self):
        logging.info('pipeline start')
        current.card.append(Markdown('# Timestamp'))
        current.card.append(Table([['first', 'second'],
                                   [1, 2]]))
        self.next(xxx)
```
2. run the pipeline with metaflow
3. open the metaflow ui and check the task in `start` step

**Expected behavior:**
The card should display with correct height
![image](https://user-images.githubusercontent.com/8553710/178662986-efa7fcd9-9730-4efa-99de-a303a4a9e478.png)

**Actual behavior:**
It displayed a card iframe with height == 0px
![image](https://user-images.githubusercontent.com/8553710/178663053-4b6d8ec6-2429-4ace-8dad-e830b712a127.png)

**Reproduces how often:**
always

### Versions

metaflow-ui v1.1.3
metaflow==2.7.1
metaflow-card-html==1.0.1

### Additional Information

None

**Comment by obgibson** [comment]
Do you know your version of metaflow-service?

**Comment by PytLab** [comment]
> Do you know your version of metaflow-service?

I'm using metaflow-service v2.2.2. Is this display issue related to metaflow also?

**Comment by obgibson** [comment]
I don't think so. I have seen similar issues before with mismatched metaflow-service and metaflow-ui which is why I asked the version.

I will see if I can recreate.

**Comment by stevenhoelscher** [comment]
I'm experiencing the same issue:

```
metaflow-ui v1.1.2
metaflow-service v2.3.0
```

**Comment by obgibson** [comment]
Unfortunately it workedforme

<img width="1421" alt="Screen Shot 2022-07-21 at 7 29 53 AM" src="https://user-images.githubusercontent.com/93726128/180085643-b178f191-797a-4e35-9334-b7ea0b2d9b5d.png">

running

    from metaflow import FlowSpec, step, Parameter, card, current
    from metaflow.cards import Markdown, Table
  
     class DumbFlow(FlowSpec):
  
      str_param = Parameter("str-param", default="something comes here")
  
      @card(type="blank")
      @step
      def start(self):
          current.card.append(Markdown("# Timestamp"))
          current.card.append(Table([["first", "second"], [1, 2]]))
          self.next(self.x, self.y)
  
      @step
      def x(self):
          """Join the topmoist foreach."""
          import random
  
          self.t = random.randint(0, 100)
          self.next(self.join)
  
      @step
      def y(self):
          """The Y step is really important so it has to have a very long description that is likely to overflow and show a tooltip and help cursor."""
          self.t = 200
          self.next(self.join)
  
      @step
      def join(self, inputs):
          ts = []
          (inputs.x.t, inputs.y.t)
          for x in inputs:
              ts.append(x.t)
          self.t = max(ts)
          self.next(self.end)
  
      @step
      def end(self):
          print("Done")
  
    if __name__ == "__main__":
        DumbFlow()

**Comment by obgibson** [comment]
The code that sets the iframe height is 

    // Check iframe height every second in case it changes somehow.
    useEffect(() => {
      setInterval(() => {
        if (ref.current) {
          const body = ref.current.contentWindow?.document.body;
          const h = Math.max(body?.scrollHeight ?? 0, body?.clientHeight ?? 0, body?.offsetHeight ?? 0);
          if (h) {
            setElementHeight(h);
          }
        }
      }, CHECK_HEIGHT_INTERVAL);
    }, []);

It would be helpful if you could put a debugging breakpoint in that function e.g.

<img width="1099" alt="Screen Shot 2022-07-21 at 7 43 26 AM" src="https://user-images.githubusercontent.com/93726128/180087595-14d5b9df-009a-4e07-a1fd-e7e660c5c723.png">

and then see if it is working correctly.

I tried to replicate using Chrome - what browser were you using?

**Comment by stevenhoelscher** [comment]
> @stevenhoelscher is your domain for the page and the iframe different?
> Mine are both http://localhost:3001/

Yeah, my input is a likely a distraction for the OP's issue, sorry!

The UI is hosted at `https://metaflow.nonprod.<company>.app` and the Metaflow UI backend service is hosted at `https://metaflow-ui-svc.nonprod.<company>.app`.

Right now, I have to click the download button to see the card or change the iframe's height in the HTML 😅 .

Is there any way to solve this issue?

**Comment by obgibson** [comment]
I don't think your input is a distraction. I think it is probably the cause of the issue.

 @PytLab can you see if your browser domain and iframe domain differ?

In the plugins code this problem has been solved by having the host send a postMessage to the iframe content which returns its height. That may have to be the approach to fix this bug.

**Comment by stevenhoelscher** [comment]
Confirming that your PR fixed my issue, thank you! @obgibson
