### ISSUE TITLE
DAG view does not auto update

### ISSUE THREAD

**Issue by romain-intel** [Netflix/metaflow-ui#77]
### Description

The colors on the DAG view to show the progression of execution do not update even if websocket is properly connected

### Steps to Reproduce

1. Go to a fairly large run
2. Go to the DAG view
3. Notice that the colors do not change unless you reload the page

**Expected behavior:**

DAG view updates state of tasks just like timeline would

**Actual behavior:**

It doesn't update

**Reproduces how often:**

All the time

### Versions

1.1.3

### Additional Information

None

**Comment by obgibson** [comment]
Should be fixed in v1.2.4
